In [22]:
f=open("사과나무in1.txt","r")
n=int(f.readline())
a = [list(map(int,f.readline().split()))for _ in range(n)]

sum = 0
s=e=n//2 #시작은 s index, 마지막은 e index
for i in range(n):
    for j in range(s,e+1):
        sum=sum+a[i][j]
    if i < n//2:
        s=s-1 ; e=e+1
    else :
        s=s+1 ; e=e-1
print(sum)
f.close()

1049


In [33]:
def N_Matirx(n):
    import random
    
    
    random.seed(0)
    return[[random.randint(1,n*n) for i in range(n)]for j in range(n)]

In [34]:
x = 3
m1=N_Matirx(x)
for i in range(x):
    print(m1[i])

[7, 7, 1]
[5, 9, 8]
[7, 5, 8]


In [29]:
import numpy as np
n = int(input("n*n 마방진을 위한 n값을 입력(3이상, 홀수인)="))
matrix = np.zeros((n,n),dtype=int)

s_row=0; s_col=n//2
matrix[s_row, s_col]=1
row=0 ; col=0

for i in range(2, n*n+1):
    row = s_row # 전 위치값 row값 보관
    col = s_col # 전 위치값 col값 보관
    s_row = s_row -1 ; s_col = s_col +1
    if s_row <0 :
        s_row = n-1
    if s_col >n-1:
        s_col= 0
        
    if matrix[s_row, s_col] == 0:
        matrix[s_row, s_col]= i
    else : #0이 아니면 다른 숫자가 있다는 이야기
        s_row = row+1 ; s_col = col
        matrix[s_row, s_col] = i

print(matrix)

n*n 마방진을 위한 n값을 입력(3이상, 홀수인)=7
[[30 39 48  1 10 19 28]
 [38 47  7  9 18 27 29]
 [46  6  8 17 26 35 37]
 [ 5 14 16 25 34 36 45]
 [13 15 24 33 42 44  4]
 [21 23 32 41 43  3 12]
 [22 31 40 49  2 11 20]]


In [30]:
matrix

array([[30, 39, 48,  1, 10, 19, 28],
       [38, 47,  7,  9, 18, 27, 29],
       [46,  6,  8, 17, 26, 35, 37],
       [ 5, 14, 16, 25, 34, 36, 45],
       [13, 15, 24, 33, 42, 44,  4],
       [21, 23, 32, 41, 43,  3, 12],
       [22, 31, 40, 49,  2, 11, 20]])